/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-01 18:14:47 UTC)
 * on 2014-04-12 at 20:55:45 UTC 
 * Modify at your own risk.
 */

package com.example.rehab_coachv1.feedbackendpoint.model;

/**
 * Model definition for Feedback.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the feedbackendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Feedback extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer activityID;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer response1;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer response2;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer response3;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer response4;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer response5;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String userID;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getActivityID() {
    return activityID;
  }

  /**
   * @param activityID activityID or {@code null} for none
   */
  public Feedback setActivityID(java.lang.Integer activityID) {
    this.activityID = activityID;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Feedback setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getResponse1() {
    return response1;
  }

  /**
   * @param response1 response1 or {@code null} for none
   */
  public Feedback setResponse1(java.lang.Integer response1) {
    this.response1 = response1;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getResponse2() {
    return response2;
  }

  /**
   * @param response2 response2 or {@code null} for none
   */
  public Feedback setResponse2(java.lang.Integer response2) {
    this.response2 = response2;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getResponse3() {
    return response3;
  }

  /**
   * @param response3 response3 or {@code null} for none
   */
  public Feedback setResponse3(java.lang.Integer response3) {
    this.response3 = response3;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getResponse4() {
    return response4;
  }

  /**
   * @param response4 response4 or {@code null} for none
   */
  public Feedback setResponse4(java.lang.Integer response4) {
    this.response4 = response4;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getResponse5() {
    return response5;
  }

  /**
   * @param response5 response5 or {@code null} for none
   */
  public Feedback setResponse5(java.lang.Integer response5) {
    this.response5 = response5;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getUserID() {
    return userID;
  }

  /**
   * @param userID userID or {@code null} for none
   */
  public Feedback setUserID(java.lang.String userID) {
    this.userID = userID;
    return this;
  }

  @Override
  public Feedback set(String fieldName, Object value) {
    return (Feedback) super.set(fieldName, value);
  }

  @Override
  public Feedback clone() {
    return (Feedback) super.clone();
  }

}
